version: "3"
services:
  mysql:
    container_name: mysql8
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password    
    ports:
      - 3306:3306
    restart: always
    # env_file: ./
    environment:
    # Use tools like godotenv (github.com/joho/godotenv), to load environment before docker-compose.
    # Inastall: go install github.com/joho/godotenv
    # Check build config: godotenv -f ./{env-file} docker-compose config
    # Target MySQL values will be build for different environments (dev/test)
    # And you should remember what is the type of container you have after it has stopped before next start.
      MYSQL_DATABASE: "${AURA_COUNTER_DB_NAME}${TEST_COUNTER_DB_NAME}"
      MYSQL_USER: "${AURA_COUNTER_DB_USER}${TEST_COUNTER_DB_USER}"
      MYSQL_PASSWORD: "${AURA_COUNTER_DB_PASSWORD}${TEST_COUNTER_DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "rootpassword"
